// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_OPENAI      Provider = 1
	Provider_PROVIDER_GEMINI      Provider = 2
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_OPENAI",
		2: "PROVIDER_GEMINI",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_OPENAI":      1,
		"PROVIDER_GEMINI":      2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_service_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_api_proto_v1_service_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{0}
}

type LLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Provider      Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=v1.Provider" json:"provider,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRequest) Reset() {
	*x = LLMRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequest) ProtoMessage() {}

func (x *LLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequest.ProtoReflect.Descriptor instead.
func (*LLMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *LLMRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *LLMRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *LLMRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *LLMRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type LLMResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ProviderUsed     string                 `protobuf:"bytes,2,opt,name=provider_used,json=providerUsed,proto3" json:"provider_used,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLMResponse) Reset() {
	*x = LLMResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMResponse) ProtoMessage() {}

func (x *LLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMResponse.ProtoReflect.Descriptor instead.
func (*LLMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *LLMResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LLMResponse) GetProviderUsed() string {
	if x != nil {
		return x.ProviderUsed
	}
	return ""
}

func (x *LLMResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_api_proto_v1_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/service.proto\x12\x02v1\"\x8f\x01\n" +
	"\n" +
	"LLMRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12(\n" +
	"\bprovider\x18\x02 \x01(\x0e2\f.v1.ProviderR\bprovider\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\"z\n" +
	"\vLLMResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rprovider_used\x18\x02 \x01(\tR\fproviderUsed\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x03R\x10processingTimeMs*N\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_OPENAI\x10\x01\x12\x13\n" +
	"\x0fPROVIDER_GEMINI\x10\x022?\n" +
	"\n" +
	"LLMService\x121\n" +
	"\x0eProcessRequest\x12\x0e.v1.LLMRequest\x1a\x0f.v1.LLMResponseB/Z-github.com/willexm1/go-llm-nexus/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_service_proto_rawDescOnce sync.Once
	file_api_proto_v1_service_proto_rawDescData []byte
)

func file_api_proto_v1_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_service_proto_rawDesc), len(file_api_proto_v1_service_proto_rawDesc)))
	})
	return file_api_proto_v1_service_proto_rawDescData
}

var file_api_proto_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_service_proto_goTypes = []any{
	(Provider)(0),       // 0: v1.Provider
	(*LLMRequest)(nil),  // 1: v1.LLMRequest
	(*LLMResponse)(nil), // 2: v1.LLMResponse
}
var file_api_proto_v1_service_proto_depIdxs = []int32{
	0, // 0: v1.LLMRequest.provider:type_name -> v1.Provider
	1, // 1: v1.LLMService.ProcessRequest:input_type -> v1.LLMRequest
	2, // 2: v1.LLMService.ProcessRequest:output_type -> v1.LLMResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_service_proto_init() }
func file_api_proto_v1_service_proto_init() {
	if File_api_proto_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_service_proto_rawDesc), len(file_api_proto_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_service_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_service_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1_service_proto = out.File
	file_api_proto_v1_service_proto_goTypes = nil
	file_api_proto_v1_service_proto_depIdxs = nil
}
